### ISSUE TITLE
getting crash on flutter web

### ISSUE THREAD

**Issue by kalaganov** [dylanshine/sendgrid_mailer#9]
I copy-pasted an example, added my own api key and got this when tried to run it on Flutter web (chrome)
```
Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28                get current
packages/http/src/browser_client.dart 71:22                                       <fn>
dart-sdk/lib/async/zone.dart 1687:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 155:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 707:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 736:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 533:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37308:58                              <fn>


    at Object.createErrorWithStack (http://localhost:57452/dart_sdk.js:5062:12)
    at Object._rethrow (http://localhost:57452/dart_sdk.js:37680:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57452/dart_sdk.js:37676:13)
    at Object._microtaskLoop (http://localhost:57452/dart_sdk.js:37533:13)
    at _startMicrotaskLoop (http://localhost:57452/dart_sdk.js:37539:13)
    at http://localhost:57452/dart_sdk.js:33289:9

```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.3.0-1.0.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)
```
```
    final mailer = Mailer('my api key');
    final toAddress = Address('myemail@gmail.com');
    final fromAddress = Address('myanotheremail@gmail.com');
    final content = Content('text/plain', 'Hello World!');
    final subject = 'Hello Subject!';
    final personalization = Personalization([toAddress]);

    final email = Email([personalization], fromAddress, subject, content: [content]);
    mailer.send(email).then((result) {
      print('----------------------- $result');
    });
```

**Comment by vishvaRam** [comment]
How did you solved it?
